import {Tektur } from "next/font/google";
import "./globals.css";
import Provider from "./Provider";

const tektur=Tektur({
  subsets: ["latin"],

})
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={tektur.className} 
      >
        <Provider>
        {children}
        </Provider>
  
      </body>
    </html>
  );
}
